import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { MarketplaceHeader } from '../components/MarketplaceHeader'
import { useAuth } from '../features/auth/useAuth'
import { useCart } from '../features/cart/useCart'
import { createOrder } from '../services/orderService'
import { useToast } from '../features/toast/useToast'

export function CheckoutPage() {
  const navigate = useNavigate(); const { firebaseUser } = useAuth(); const { dispatch, items, total } = useCart(); const { showToast } = useToast(); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false)
  if (items.length === 0) return <main className="min-h-screen bg-[var(--page)]"><MarketplaceHeader /><section className="px-4 py-16 text-center"><h1 className="font-[Space_Grotesk] text-3xl font-bold text-[var(--text)]">No hay productos para confirmar</h1><Link className="mt-8 inline-block rounded-xl bg-[var(--royal-violet)] px-5 py-3 font-semibold text-white" to="/catalog">Volver al catalogo</Link></section></main>
  async function handleConfirm() { if (!firebaseUser || isSubmitting) return; setError(''); setIsSubmitting(true); try { const orderId = await createOrder(firebaseUser.uid, items); dispatch({ type: 'CLEAR_CART' }); showToast('Compra confirmada correctamente.', 'success'); navigate(`/orders/${orderId}`, { replace: true }) } catch (checkoutError) { const message = checkoutError instanceof Error && checkoutError.message.startsWith('INSUFFICIENT_STOCK') ? 'Algunos productos ya no tienen suficiente stock. Ajusta tu carrito e intenta nuevamente.' : 'No pudimos crear la orden. Tu carrito sigue intacto; intenta nuevamente.'; setError(message); showToast(message, 'error') } finally { setIsSubmitting(false) } }
  return <main className="min-h-screen bg-[var(--page)]"><MarketplaceHeader /><div className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><Link className="font-semibold text-[var(--royal-violet)]" to="/cart">← Volver al carrito</Link><section className="mt-8 rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[var(--text-muted)]">Checkout simulado</p><h1 className="mt-2 font-[Space_Grotesk] text-3xl font-bold text-[var(--text)]">Confirma tu compra</h1><div className="mt-8 space-y-3">{items.map((item) => <div className="flex items-center justify-between border-b border-[var(--border)] pb-3 text-sm" key={item.productId}><span>{item.name} x {item.quantity}</span><span className="font-semibold">${(item.price * item.quantity).toLocaleString('es-AR')}</span></div>)}</div><div className="mt-6 flex items-center justify-between text-xl font-bold text-[var(--text)]"><span>Total</span><span className="text-[var(--royal-violet)]">${total.toLocaleString('es-AR')}</span></div>{error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-[var(--danger)]" role="alert">{error}</p>}<button className="mt-8 w-full rounded-xl bg-[var(--royal-violet)] px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={isSubmitting || !firebaseUser} onClick={handleConfirm} type="button">{isSubmitting ? 'Creando orden...' : 'Confirmar compra'}</button>{!firebaseUser && <p className="mt-3 text-center text-sm text-[var(--text-muted)]">Inicia sesion para confirmar tu compra.</p>}</section></div></main>
}